export enum ProcessQueueLogStepEnum {
    VALIDATION = 'VALIDATION',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    ERROR = 'ERROR',
    RPA_EXECUTION = 'RPA_EXECUTION',
    DATA_EXTRACTION = 'DATA_EXTRACTION',
    DATA_MAPPING = 'DATA_MAPPING',
    DATABASE_SAVE = 'DATABASE_SAVE',
    BALANCE_UPDATE = 'BALANCE_UPDATE',
}